### PR TITLE
This might work

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
the images for the site docs

### CODE REVIEW

**Comment by hemisemidemipresent** [comment]
hmm the pages dont build

**Comment by hemisemidemipresent** [comment]
Yeah the pages error is a bit strange, the pages got built but the deploy had an error, I assume since the pages got built its fine

**Comment by hemisemidemipresent** [comment]
Yeah BowDown's PR also failed the site deployment check so it should be fine

**Comment by DisabledMallis** [comment]
Its ok, its bc you dont have write access to the branch on the repo

**Comment by hemisemidemipresent** [comment]
btw what is the command for testing site deployment?

**Comment by DisabledMallis** [comment]
npm run build - for building
npm run dev - for testing

**Pull request merged**
